name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Mude para 'master' se a sua branch principal tiver esse nome

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Compilar o projeto Angular
        run: npx ng build --configuration production --base-href /Lilium/

      - name: Enviar para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/Lilium/browser/index.html
          branch: gh-pages
